typography_spectrum: 0.26423
content_rating:
  adult: false
color:
  brandColors:
    - '#f4f4f4'
    - '#e33e2b'
    - '#2ba14b'
    - '#3a7cec'
    - '#f1b500'
  brandStrength: 0.9821608234196901
  lightness: 0.3645698812324554
  saturation: 0.3408927589189261
  rhythmicContrast: 0.19100137962959707
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.65159
analytics:
  google: UA-83275935-1
author:
  name: ''
  url: ModernAristocrats.ca
  email: modernaristocrats15@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/349b45ae-d6df-4872-8092-1bae8369bc9d.jpg
name: Modern Aristocrats
cta: {}
navigation:
  - name: Canadian Finance
    id: 01c14788-56e2-4dd0-a2ad-9ef4460db53e
    type: content
title: Finance & Lifestyle Media Hub
purpose: []
