name: Modern Aristocrats
favicon: null
layout_spectrum: 0.65159
typography_spectrum: 0.9096461278386414
title: Financial & Luxury Media Hub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#007468'
    - '#009100'
    - '#002a14'
    - '#164044'
  brandStrength: 0.9821608234196901
  lightness: 0.3645698812324554
  saturation: 0.3408927589189261
  rhythmicContrast: 0.19100137962959707
purpose: []
